#!/usr/bin/env python3
'''
Simple script digging out modules= from the /etc/lirc_options file, and
runs modprobe on all modules listed there. Return code from
modprobe.

A single argument is accepted which overrides the default location
/etc/lirc/lirc_options.conf
'''

import configparser
import subprocess
import sys


_LIRC_OPTIONS = '/etc/lirc/lirc_options.conf'


def main():
    ''' Well, well...Indeed: the main program. '''
    if len(sys.argv) > 1:
        path = sys.argv[1]
    else:
        path = _LIRC_OPTIONS

    config = configparser.RawConfigParser()
    config.read(path)

    try:
        modules = config.get('modprobe', 'modules')
    except (configparser.NoOptionError, configparser.NoSectionError):
        sys.exit(0)
    if not modules:
        sys.exit(0)

    cmd = ['modprobe']
    cmd.extend(modules.split())
    p = subprocess.Popen(cmd)
    p.communicate()
    sys.exit(p.returncode)

main()

#                                             vim: set expandtab ts=4 sw=4:
